-- Run once as ACCOUNTADMIN, then switch the application to MAVIS_APP_ROLE.
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS MAVIS_APP_ROLE;
CREATE WAREHOUSE IF NOT EXISTS MAVIS_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;
CREATE DATABASE IF NOT EXISTS MAVIS;
CREATE SCHEMA IF NOT EXISTS MAVIS.PUBLIC;
CREATE STAGE IF NOT EXISTS MAVIS.PUBLIC.MAVIS_IMAGES
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  DIRECTORY = (ENABLE = TRUE);

GRANT USAGE ON WAREHOUSE MAVIS_WH TO ROLE MAVIS_APP_ROLE;
GRANT USAGE ON DATABASE MAVIS TO ROLE MAVIS_APP_ROLE;
GRANT USAGE ON SCHEMA MAVIS.PUBLIC TO ROLE MAVIS_APP_ROLE;
GRANT READ, WRITE ON STAGE MAVIS.PUBLIC.MAVIS_IMAGES TO ROLE MAVIS_APP_ROLE;

GRANT USE AI FUNCTION AI_COMPLETE ON ACCOUNT TO ROLE MAVIS_APP_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.AI_FUNCTIONS_USER TO ROLE MAVIS_APP_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.USAGE_VIEWER TO ROLE MAVIS_APP_ROLE;

-- Model access is RBAC-managed. Inspect current roles, then grant only the two used models.
CALL SNOWFLAKE.MODELS.CORTEX_BASE_MODELS_REFRESH();
SHOW CORTEX BASE MODELS IN SCHEMA SNOWFLAKE.MODELS;
SHOW APPLICATION ROLES LIKE 'CORTEX-MODEL%' IN APPLICATION SNOWFLAKE;

-- Example only; replace with role names returned above:
-- GRANT APPLICATION ROLE SNOWFLAKE."CORTEX-MODEL-GEMINI-2.5-FLASH-LITE"
--   TO ROLE MAVIS_APP_ROLE;
-- GRANT APPLICATION ROLE SNOWFLAKE."CORTEX-MODEL-GEMINI-3.1-PRO"
--   TO ROLE MAVIS_APP_ROLE;

-- Grant the role to the application user manually:
-- GRANT ROLE MAVIS_APP_ROLE TO USER <YOUR_USER>;

USE ROLE MAVIS_APP_ROLE;
USE WAREHOUSE MAVIS_WH;
USE DATABASE MAVIS;
USE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS RUNS (
  RUN_ID STRING,
  CLIP_ID STRING,
  STRATEGY STRING,
  ACTION STRING,
  MODEL STRING,
  QUERY_ID STRING,
  PREDICTION STRING,
  GROUND_TRUTH STRING,
  CORRECT BOOLEAN,
  LATENCY_MS FLOAT,
  ESTIMATED_CREDITS FLOAT,
  ACTUAL_CREDITS FLOAT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
