SELECT
  QUERY_TAG,
  QUERY_ID,
  MODEL_NAME,
  F.VALUE:key:metric::STRING AS METRIC,
  F.VALUE:key:unit::STRING AS UNIT,
  SUM(F.VALUE:value::NUMBER) AS VALUE,
  SUM(CREDITS) AS AI_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AI_FUNCTIONS_USAGE_HISTORY H,
LATERAL FLATTEN(INPUT => H.METRICS) F
WHERE QUERY_TAG LIKE 'mavis|%'
GROUP BY 1, 2, 3, 4, 5
ORDER BY QUERY_TAG, QUERY_ID, METRIC;
